ScoolSolution/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using ScoolSolution.Models;
using ScoolSolution.Repository;

namespace ScoolSolution.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly ITeacherRepository _teacherRepository;
        public CourseController(ICourseRepository courseRepository, ITeacherRepository teacherRepository)
        {
            _courseRepository = courseRepository;
            _teacherRepository = teacherRepository;
        }
        [HttpGet]
        public ActionResult Index()
        {
            List<Course> courseLst = _courseRepository.GetAllCourses();
            return View(courseLst);
        }
        [HttpGet]
        public ViewResult Create()
        {
            List<Teacher> teacherLst = _teacherRepository.GetAllTeachers();
            return View(teacherLst);
        }
        [HttpPost]
        public ActionResult Create(Course course)
        {
            if (course != null)
            {
                _courseRepository.Create(course);
            }
            List<Course> courseLst = _courseRepository.GetAllCourses();
            return View("index", courseLst);
        }
        public ActionResult Delete(int id)
        {
            if (id > 0)
            {
                _courseRepository.Delete(id);
            }
            List<Course> courseLst = _courseRepository.GetAllCourses();
            return View("index", courseLst);
        }
    }
}

ScoolSolution/Controllers/RoomController.cs
using Microsoft.AspNetCore.Mvc;
using ScoolSolution.Models;
using ScoolSolution.Repository;

namespace ScoolSolution.Controllers
{
    public class RoomController : Controller
    {
        private readonly IRoomRepository _roomRepository;

        public RoomController(IRoomRepository roomRepository)
        {
            _roomRepository = roomRepository;
        }
        [HttpGet]
        public ActionResult Index()
        {
            List<Room> roomLst = _roomRepository.GetAllRooms();
            return View(roomLst);
        }
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Room room)
        {
            if (room != null)
            {
                _roomRepository.Create(room);
            }
            List<Room> roomLst = _roomRepository.GetAllRooms();
            return View("Index",roomLst);
        }
        public ActionResult Delete(int id)
        {
            if (id > 0)
            {
                _roomRepository.Delete(id);
            }
            List<Room> roomLst = _roomRepository.GetAllRooms();
            return View("Index", roomLst);
        }
    }
}

ScoolSolution/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using ScoolSolution.Models;
using ScoolSolution.Models.ViewModels;
using ScoolSolution.Repository;
using Microsoft.AspNetCore.Hosting;


namespace ScoolSolution.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentRepository _studentRepository;
        private readonly ICourseRepository _courseRepository;
        private readonly IHostEnvironment  _environment;

        public StudentController(IStudentRepository studentRepository, 
                                 ICourseRepository courseRepository, IHostEnvironment environment)
        {
            _studentRepository = studentRepository;
            _courseRepository = courseRepository;
            _environment = environment;
        }

        //list of students
        [HttpGet]
        public ActionResult Index()
        {
            List<Student> studentLst = _studentRepository.GetAllStudents() ;
            return View(studentLst);
        }
        //render the creation view
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Student student, IFormFile StudentPhoto)
        {
                var wwRootPath = _environment.ContentRootPath + "/wwwroot/StudentPictures/";
                Guid guid = Guid.NewGuid();
                string fullPath= System.IO.Path.Combine(wwRootPath,guid+ StudentPhoto.FileName);
                using (var fileStream = new FileStream(fullPath, FileMode.Create))
                {
                    StudentPhoto.CopyTo(fileStream);
                };

                student.PhotoName = guid + StudentPhoto.FileName;
                _studentRepository.Create(student);
                List<Student> studentLst = _studentRepository.GetAllStudents();
                return View("Index",studentLst);
        }
        public ViewResult Delete(int id)
        {
            if (id > 0)
            {
                _studentRepository.Delete(id);
            }
            List<Student> studentLst = _studentRepository.GetAllStudents();
            return View("Index",studentLst);
        }
        [HttpGet]
        public ActionResult Register()
        {

            StudentCourseVM data = new StudentCourseVM();
            data.Courses = _courseRepository.GetAllCourses();
            data.Students = _studentRepository.GetAllStudents();
            return View(data);
        }
        [HttpPost]
        public ActionResult Register (int studentid, int courseid)
        {
            TempData["test"] = 10;

            _studentRepository.Register(studentid, courseid);
            return RedirectToAction("Register");
        }
    }
}

ScoolSolution/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using ScoolSolution.Models;
using ScoolSolution.Repository;

namespace ScoolSolution.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherRepository _teacherRepository;

        public TeacherController(ITeacherRepository teacherRepository)
        {
            _teacherRepository = teacherRepository;
        }

        //list of Teachers
        [HttpGet]
        public ActionResult Index()
        {
            List<Teacher> teacherLst = _teacherRepository.GetAllTeachers();
            return View(teacherLst);
        }
        //render the creation view
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Teacher teacher)
        {
            if (teacher != null)
            {
                _teacherRepository.Create(teacher);
            }
            List<Teacher> teacherLst = _teacherRepository.GetAllTeachers();
            return View("Index", teacherLst);
        }
        public ViewResult Delete(int id)
        {
            if (id > 0)
            {
                _teacherRepository.Delete(id);
            }
            List<Teacher> teacherLst = _teacherRepository.GetAllTeachers();
            return View("Index", teacherLst);
        }
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
    }
}

ScoolSolution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ScoolSolution</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ScoolSolution.styles.css" asp-append-version="true" />
    <link href="~/css/form.css" rel="stylesheet" />
    <link href="~/css/table.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ScoolSolution</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="Index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Register">Register student</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ScoolSolution - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>